stages:
  - install
  - build
  - test
  - publish
variables:
  DOCKER_HOST: tcp://gitlab-prod-dind-svc:2375

install:
  stage: install
  image: node:12.13
  script:
    - yarn install
    - yarn run bootstrap
  artifacts:
    paths:
      - "node_modules"
      - "packages/*/node_modules"
      - "packages/cli/resources/templates/*/node_modules"

build:
  stage: build
  image: node:12.13

  script:
    - yarn run build

  artifacts:
    paths:
      - "packages/*/dist"
      - "packages/*/migrations/*.js"

test:
  stage: test
  image: node:12.13
  services:
    - postgres:10
  variables:
    TEST_DB_HOST: 127.0.0.1
    TEST_DB_PASSWORD: "123"
    TEST_DB_USER: cms_test
    TEST_DB_NAME: cms_test
    TEST_DB_NAME_TENANT: cms_test_tenant
    TEST_DB_PORT: 5432
    POSTGRES_USER: cms_test
    POSTGRES_DB: cms_test
    POSTGRES_PASSWORD: "123"

  script:
    - yarn run test

eslint:
  stage: test
  image: node:12.13
  script:
    - yarn run eslint:lint

publish:npm:
  image: node:12.13
  stage: publish
  dependencies:
    - build
  only:
    - tags
  script:
    - bash ./scripts/npm/publish.sh

publish:docker:
  image: docker:19
  stage: publish
  dependencies:
    - build
  only:
    - tags
  variables:
    VERSION: "$CI_COMMIT_REF_NAME"
  script:
    - docker login --username $DOCKER_USER --password $DOCKER_PASSWORD
    - apk --no-cache add git bash
    - bash scripts/docker/build.sh
