version: '3.7'
services:
  ts_watch:
    image: node:14
    volumes:
      - ./:/src:cached
    working_dir: /src
    command: yarn run ts:watch

  db:
    image: postgres:10-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: contember
      POSTGRES_USER: contember
      POSTGRES_DB: contember
    volumes:
    - pgsql-data:/var/lib/postgresql/data
  api:
    image: node:14
    working_dir: /src
    volumes:
      - .:/src
    environment:
      NODE_ENV: development
      CONTEMBER_PORT: 4000
      CONTEMBER_MONITORING_PORT: 4001
      CONTEMBER_ROOT_EMAIL: 'admin@localhost'
      CONTEMBER_ROOT_PASSWORD: 'admin@localhost'
      CONTEMBER_ROOT_TOKEN: '0000000000000000000000000000000000000000'
      CONTEMBER_LOGIN_TOKEN: '1111111111111111111111111111111111111111'
      DEFAULT_DB_HOST: 'db'
      DEFAULT_DB_PORT: '5432'
      DEFAULT_DB_USER: 'contember'
      DEFAULT_DB_PASSWORD: 'contember'
      TEST_DB_HOST: 'db'
      TEST_DB_PORT: '5432'
      TEST_DB_USER: 'contember'
      TEST_DB_PASSWORD: 'contember'
      TENANT_DB_NAME: 'tenant'
      CONTEMBER_TENANT_MIGRATIONS_DIR: /src/packages/engine-tenant-api/migrations
      CONTEMBER_SYSTEM_MIGRATIONS_DIR: /src/packages/engine-system-api/migrations
    command:
      - node
      - ./packages/engine-server/dist/src/start.js
volumes:
  pgsql-data: ~
