version: '3'

services:
  sandbox_vite:
    image: 'alpine'
    command: ['sleep', 'infinity']

  admin_server:
    image: 'alpine'
    command: ['sleep', 'infinity']

  admin_server_esbuild:
    image: 'alpine'
    command: ['sleep', 'infinity']

  admin_server_vite:
    image: 'alpine'
    command: ['sleep', 'infinity']

  api:
    ports: ['5001:4000']

  adminer:
    ports: ['5002:8080']

  s3:
    command: 'server --address :5003 /data'
    ports: ['5003:5003']

  postgres:
    ports: ['5005:5432']
