version: '3'

services:
  sandbox_vite:
    user: '1000:1000'
    ports: ['5000:5000']

  admin_server:
    user: '1000:1000'
    ports: ['5006:4000']

  admin_server_esbuild:
    user: '1000:1000'

  admin_server_vite:
    user: '1000:1000'

  api:
    ports: ['5001:4000']

  adminer:
    ports: ['5002:8080']

  s3:
    command: 'server --address :5003 /data'
    ports: ['5003:5003']

  postgres:
    ports: ['5005:5432']
