name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches-ignore:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:16-alpine

    steps:
      - uses: actions/checkout@v2
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run eslint:lint
      - run: pnpm run build
      - run: pnpm run test
