name: Build
on:
  push:
    branches: [ 'main' ]
    tags: [ '**' ]
  pull_request:
    paths-ignore:
      - docs/**
  workflow_dispatch:

jobs:

  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: '20'

      - name: Install yarn deps
        run: |
          yarn --version
          yarn install --immutable

  check:
    needs: [install]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:

          - job_name: eslint
            run_script: yarn run eslint:lint

          - job_name: build
            run_script: yarn run build

          - job_name: api-exporter
            run_script: |
              yarn run ts:build
              yarn run ae:test

          - job_name: lint-imports
            run_script: yarn tsx ./scripts/lint/module-import-linter.ts

          - job_name: dedupe
            run_script: yarn dedupe --check
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: '20'

      - name: Install yarn deps
        run: |
          yarn --version
          yarn install --immutable

      - name: Run ${{ matrix.job_name }}
        run: ${{ matrix.run_script }}

  test:
    needs: [ install ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres: [11, 12, 13, 14, 15, 16]
    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: '20'
      - name: Install yarn deps
        run: |
          yarn --version
          yarn install --immutable
      - name: "Build app"
        run: yarn run build
      - name: "Run tests"
        run: yarn run test
        env:
          TEST_DB_HOST: 127.0.0.1
          TEST_DB_PASSWORD: postgres
          TEST_DB_USER: postgres
          TEST_DB_NAME: test
          CONTEMBER_ROOT_TOKEN: '0000000000000000000000000000000000000000'
          CONTEMBER_LOGIN_TOKEN: '1111111111111111111111111111111111111111'
      - name: Start server
        run: ./packages/engine-server/tests/start-server.sh
        env:
          DEFAULT_DB_HOST: 127.0.0.1
          DEFAULT_DB_PASSWORD: postgres
          DEFAULT_DB_USER: postgres
          DEFAULT_DB_PORT: 5432
          TENANT_DB_NAME: test_tenant
          CONTEMBER_PORT: 4000
          CONTEMBER_MONITORING_PORT: 4001
          CONTEMBER_ROOT_TOKEN: '0000000000000000000000000000000000000000'
          CONTEMBER_LOGIN_TOKEN: '1111111111111111111111111111111111111111'
      - name: "Run E2E tests"
        run: yarn run test-e2e
        env:
          CONTEMBER_API_URL: "http://localhost:4000"
          CONTEMBER_ROOT_TOKEN: '0000000000000000000000000000000000000000'
          CONTEMBER_LOGIN_TOKEN: '1111111111111111111111111111111111111111'
