name: Publish

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup node
        uses: actions/setup-node@main
        with:
          node-version: 16
          cache: pnpm
          registry-url: https://verdaccio.mgw.cz/
          scope: @contember

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run eslint:lint

      - name: Build
        run: pnpm run build

      - name: Build API
        run: pnpm run build:api:dev

      - name: Test
        run: pnpm run test

      - name: Publish NPM
        run: |
          pnpm config set git-tag-version false
          pnpm recursive exec npm version "${GITHUB_REF:11}"
          pnpm recursive publish --access restricted --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.VERDACCIO_NPM_TOKEN }}
