name: Publish Canary build

on:
  workflow_dispatch:

jobs:
  publish-canary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Publish Docker Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login --username "$DOCKER_USER" --password "$DOCKER_PASSWORD"
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --file ee/admin-server/Dockerfile \
            --cache-from type=registry,ref=ghcr.io/contember/admin \
            --cache-to   type=registry,ref=ghcr.io/contember/admin,mode=max \
            --tag "contember/admin:canary-${GITHUB_SHA:10}" \
            --push \
            .
