name: Publish

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@main
        with:
          node-version: 16

      - name: Get the version
        run: echo "VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run eslint:lint

      - name: Build
        run: pnpm run build

      - name: Build API
        run: pnpm run build:api:dev

      - name: Test
        run: pnpm run test

      - name: Publish NPM
        run: cp .npmrc.dist .npmrc && pnpm publish -r --access restricted --no-git-checks
        env:
          VERDACCIO_NPM_TOKEN: ${{ secrets.VERDACCIO_NPM_TOKEN }}
