name: Publish

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup node
        uses: actions/setup-node@main
        with:
          node-version: 16
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run eslint:lint

      - name: Build
        run: pnpm run build

      - name: Build API
        run: pnpm run build:api:dev

      - name: Build Docker
        run: docker build -t "contember/admin:${GITHUB_REF:11}" -f ./ee/admin-server/Dockerfile .

      - name: Test
        run: pnpm run test

      - name: Setup node
        uses: actions/setup-node@main
        with:
          node-version: 16
          cache: pnpm

      - name: Publish NPM
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm config set git-tag-version false
          pnpm recursive exec npm version "${GITHUB_REF:11}"
          pnpm recursive publish --access public --no-git-checks

      - name: Publish Docker
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login --username "$DOCKER_USER" --password "$DOCKER_PASSWORD"
          docker push --all-tags "contember/admin"
