name: Publish Canary build
on:
  workflow_dispatch:

jobs:
  publish-canary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Get the version
        run: echo "VERSION=${GITHUB_SHA:10}" >> $GITHUB_ENV
      - name: "Build app"
        run: yarn run build
      - name: "Publish Docker"
        run: bash ./scripts/docker/build-canary.sh
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
